# Generated by Django 3.1.3 on 2020-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Eid', models.IntegerField()),
                ('Ename', models.CharField(max_length=20)),
                ('Eage', models.IntegerField()),
                ('Esal', models.IntegerField()),
                ('Desig', models.CharField(max_length=30)),
            ],
        ),
    ]
