# Generated by Django 3.1.3 on 2020-12-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('isbn_number', models.IntegerField()),
                ('published_date', models.DateField()),
                ('no_of_copies_sold', models.IntegerField()),
            ],
        ),
    ]
